---

- name: Actions for all servers
  hosts: dev
  become: yes
  vars_files:
     - "./vars/{{env}}.yaml"
  tasks:
     - name: install java 8 
       yum:
         name: "java-{{kafka.java.version}}-openjdk"
         state: latest
         
     - name: checking if line of swap=1 exists
       shell: cat /etc/sysctl.conf | grep vm.swappiness=1 | wc -l
       register: swap_1_exists

     - name: Configure swappinness
       lineinfile:
          path: /etc/sysctl.conf
          line: vm.swappiness=1
       when: swap_1_exists.stdout=="0"
     

     - name: Copy /etc/hosts
       copy:
        src: ./vars/hosts
        dest: /etc/hosts
   
     - name: Check the kafka directory exists
       stat:
         path: /home/ansible/kafka
       register: kafka_dir  
       
     - name: Download kafka (with zookeeper)
       get_url:
         url: "https://archive.apache.org/dist/kafka/{{kafka.version}}/kafka_{{kafka.scala.version}}-{{kafka.version}}.tgz"
         dest: /tmp/
       when: not kafka_dir.stat.exists
         
     - name: Extract kafka tar
       unarchive:
         src: /tmp/kafka_{{kafka.scala.version}}-{{kafka.version}}.tgz
         dest: /home/ansible/
       when: not kafka_dir.stat.exists
        
     - name:  rename kafka folder
       command: "mv /home/ansible/kafka_{{kafka.scala.version}}-{{kafka.version}} /home/ansible/kafka"
       when: not kafka_dir.stat.exists

