---

- name: Actions for all servers
  hosts: dev
  become: yes
  vars_files:
     - "./vars/{{env}}.yaml"
  tasks:

     - name: set broker id
       set_fact:
          broker_id: "{{ groups['dev'].index(inventory_hostname) + 1 }}"

     - name: Create kafka data directory
       file:
        path: /home/ansible/{{ item }}
        state: directory
       loop:
          - data/kafka/
          - prometheus/
 
     - name: Configure kafka server.properties
       template:
        src: ./kafka/server.properties.j2
        dest: /home/ansible/kafka/config/server.properties

     - name: Download JMX Prometheus agent
       get_url:
         url: "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.17.0/jmx_prometheus_javaagent-0.17.0.jar"
         dest: /home/ansible/prometheus/

     - name: Download Kafka  Prometheus config
       get_url:
         url: "https://raw.githubusercontent.com/prometheus/jmx_exporter/master/example_configs/kafka-2_0_0.yml"
         dest: /home/ansible/prometheus/


     - name: Add kafka service
       copy:
        src: ./kafka/kafka-service
        dest: /etc/systemd/system/kafka.service
        mode: u+x

     - name: Start kafka brokers
       systemd:
         state: started
         daemon_reload: yes
       tags: launch


