---

- name: Actions for all servers
  hosts: localhost
  become: yes
  vars_files:
    - "./vars/{{ env }}.yml"
  tasks:
     - name: install java 8 
       yum:
         name: "openjdk-{{kafka.java-version}}-jdk"
         state: latest

     - name: Configure swappinness
       lineinfile:
          path: /etc/sysctl.conf
          line: vm.swappiness=1
          
     - name: Configure /etc/hosts
       lineinfile:
          path: /etc/hosts
          line: " {{ servers.ip-address }} {{ servers.hostname }}"
       loop: "{{ servers }}"
     - name: Download kafka (with zookeeper)
       get_url:
         url: "https://archive.apache.org/dist/kafka/{{kafka.version}}/kafka_{{kafka.scala-version}}-{{kafka.version}}.tgz"
         dest: /tmp/
     - name: Extract foo.tgz into /var/lib/foo
       unarchive:
         src: /tmp/kafka_{{kafka.scala-version}}-{{kafka.version}}.tgz
         dest: /home/ansible/