---

- name: Actions for all servers
  hosts: dev
  become: yes
  vars_files:
     - "./vars/{{env}}.yaml"
  tasks:
     - name: install java 8 
       yum:
         name: "java-{{kafka.java.version}}-openjdk"
         state: latest
         
     - name: checking if line of swap=1 exists
       shell: cat /etc/sysctl.conf | grep vm.swappiness=1 | wc -l
       register: swap_1_exists

     - name: Configure swappinness
       lineinfile:
          path: /etc/sysctl.conf
          line: vm.swappiness=1
       when: swap_1_exists.stdout=="0"
     
     - name: checking if kafka list of hosts exists in /etc/hosts
       shell: cat /etc/hosts | grep 'kafka*\|zookeeper*' | wc -l
       register: kafka_hosts_exists
         
     - name: Configure Zookeeper /etc/hosts
       lineinfile:
          path: /etc/hosts
          line: " {{ item.ip_address }} {{ item.hostname }}"
       loop: "{{ zookeeper }}"
       when: kafka_hosts_exists.stdout=="0"

     - name: Configure Kafka /etc/hosts
       lineinfile:
          path: /etc/hosts
          line: " {{ item.ip_address }} {{ item.hostname }}"
       loop: "{{ kafka.servers }}"
       when: kafka_hosts_exists.stdout=="0"
        
     - name: Check the kafka directory exists
       stat:
         path: /home/ansible/kafka
       register: kafka_dir  
       
     - name: Download kafka (with zookeeper)
       get_url:
         url: "https://archive.apache.org/dist/kafka/{{kafka.version}}/kafka_{{kafka.scala.version}}-{{kafka.version}}.tgz"
         dest: /tmp/
       when: not kafka_dir.stat.exists
         
     - name: Extract kafka tar
       unarchive:
         src: /tmp/kafka_{{kafka.scala.version}}-{{kafka.version}}.tgz
         dest: /home/ansible/
       when: not kafka_dir.stat.exists
        
     - name:  rename kafka folder
       command: "mv /home/ansible/kafka_{{kafka.scala.version}}-{{kafka.version}} /home/ansible/kafka"
       when: not kafka_dir.stat.exists

     - name: checking if kafka list of hosts exists in /etc/hosts
       shell: chkconfig --list  | grep zookeeper | wc -l
       register: zookeeper_service_exists

     - name: Create zookeeper data directory
       file:
        path: /data/zookeeper
        state: directory
     
     - name: check if zookeeper server id exists
       shell: cat /data/zookeeper/myid | grep -E '[0-9]+' | wc -l
       register: zookeeper_id_exists

     - name: Configure zookeeper ID
       lineinfile:
          path: /data/zookeeper/myid
          create: yes
          line: "{{id}}"
       when: zookeeper_id_exists.stdout=="0"

     - name: Configure zookeeper.properties
       copy:
        src: ./zookeeper/zookeeper.properties
        dest: /home/ansible/kafka/config/zookeeper.properties

     - name: Add zookeeper service
       copy:
        src: ./zookeeper/zookeeper-service
        dest: /etc/init.d/zookeeper
        mode: u+x

     - name:  Add links between init.d and rc.d
       command: "chkconfig --add zookeeper"
       when: zookeeper_service_exists.stdout=="0"

     - name: start zookeeper 
       command: service zookeeper start
       #service: 
         #name: zookeeper
         #state: started
         #enabled: yes
       tags: launch
