---

- name: Actions for all servers
  hosts: dev
  become: yes
  vars_files:
     - "./vars/{{env}}.yaml"
  tasks:
         
     - name: Set Broker ID
       set_fact:
        broker_id: "{{ groups['dev'].index(inventory_hostname) + 1 }}"

     - name: Create zookeeper data directory
       file:
        path: /home/ansible/data/zookeeper
        state: directory
     
     
     - name: check if zookeeper server id exists
       shell: cat /home/ansible/data/zookeeper/myid | grep -E '[0-9]+' | wc -l
       register: zookeeper_id_exists

     - name: Configure zookeeper ID
       lineinfile:
          path: /home/ansible/data/zookeeper/myid
          create: yes
          line: "{{broker_id}}"
       when: zookeeper_id_exists.stdout=="0"

     - name: Configure zookeeper.properties
       copy:
        src: ./zookeeper/zookeeper.properties
        dest: /home/ansible/kafka/config/zookeeper.properties

     - name: Add zookeeper service
       copy:
        src: ./zookeeper/zookeeper-service
        dest: /etc/systemd/system/zookeeper.service
        mode: u+x

     - name: Start zookeeper nodes
       systemd:
         name: zookeeper
         state: restarted
         daemon_reload: yes
       tags: launch


